version: "3.8"
services:
  backend:
    image: "markjager13/springboot-react-fullstack:22.9.2022.20.18.37"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev